#cloud-config

package_update: true

write_files:
  - path: /etc/ssh/sshd_config
    owner: root:root
    permissions: 0600
    content: |
      Port 22
      # Use these options to restrict which interfaces/protocols sshd will bind to
      #ListenAddress ::
      #ListenAddress 0.0.0.0
      Protocol 2
      # HostKeys for protocol version 2
      HostKey /etc/ssh/ssh_host_rsa_key
      HostKey /etc/ssh/ssh_host_dsa_key
      HostKey /etc/ssh/ssh_host_ecdsa_key
      HostKey /etc/ssh/ssh_host_ed25519_key
      #Privilege Separation is turned on for security
      UsePrivilegeSeparation yes

      # To enable empty passwords, change to yes (NOT RECOMMENDED)
      PermitEmptyPasswords no

      # Change to yes to enable challenge-response passwords (beware issues with
      # some PAM modules and threads)
      ChallengeResponseAuthentication no

      # Change to no to disable tunnelled clear text passwords
      PasswordAuthentication no

      X11Forwarding yes
      X11DisplayOffset 10
      PrintMotd no
      PrintLastLog yes
      TCPKeepAlive yes
      #UseLogin no

      # Allow client to pass locale environment variables
      AcceptEnv LANG LC_*
      # Subsystem sftp /usr/lib/openssh/sftp-server
      UsePAM yes

packages:
 - awscli

runcmd:
  - [ bash, ls]