#cloud-config

package_update: true

packages:
 - apt-transport-https
 - ca-certificates
 - curl
 - software-properties-common

runcmd:
  - [ sh, -c, "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -" ]
  - [ sh, -c, "sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'" ]
  - [ sh, -c, "sudo apt-get update" ]
  - [ sh, -c, "apt-cache policy docker-ce" ]
  - [ sh, -c, "sudo apt-get --assume-yes install docker-ce" ]
  - [ sh, -c, "sudo systemctl status docker" ]
  - [ sh, -c, "sudo docker run -p 80:80 -d nginx" ]
